#spring-boot允许直接使用ymal配置来注入实体类

server:
  port: 8088

netty:
  port: 12345

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jingweimeeting?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 334331096Sql
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  mapper-locations: com/jignwei/dao/*.xml

